# Base Inventor Makefile
# Brygg Ullmer, 9/30/95

CC = CC
cc = cc
EARL_TOPDIR = /mas/vlw/u/rennison/Odyssey/Stable

#include $(EARL_TOPDIR)/lib/Paths.mk
#include $(EARL_TOPDIR)/lib/Rules.mk

#### LIBRARIES ####

INVLIBS = $(LIBS) -lInventorXt -lInventor -lGL -limage \
                  -lXirisw -lXm_s -lXt_s -lX11_s -lm 

#                  -lXirisw -lXm_s -lXt_s -lX11_s -lPW -lm 

FONTLIB = /vlw/src/libivfont-iv21/libivfont.a
FONTULIB = /vlw/src/libivutil-iv21/libivutil.a

#FLOCKLIB = -L/usr/lib/libpfdb -lpf_ogl -limage \
#   /u/dave/libFlock2.0/libFlock.a -lgl -lfpe -lfm 

# FLOCKLIB = -lpf_ogl -limage /u/dave/libFlock/libFlock.a -lgl -lfpe -lfm

FLOCKLIB = /usr/lib/Performer1.2/libpf-g.a \
   -limage /u/dave/libFlock/libFlock.a -lgl 

LEGOLIB  = /u/dave/libControlLab/libControlLab.a  \
   -rpath /usr/lib/Performer1.2 /usr/lib/Performer1.2/libpf.so \
   /usr/lib/Performer1.2/libpr.so /usr/lib/Performer1.2/libpfutil.so 


APPLIBS       = $(FONTULIB) $(FONTLIB) 

#APPLIBS       = $(EARL_TOPDIR)/lib/libbasic.a \
#		$(EARL_TOPDIR)/lib/libgu.a \
#		$(EARL_TOPDIR)/lib/libivfont.a

#LIBS         = -lGLU  -lm -lInventorXt -lm
LIBS         = -lm -lInventorXt -lm 

TCL_DIR = /vlw/pkg/tcl.installs/tcllib
TCL_INCLUDE = -I$(TCL_DIR)/include
TCL_LIB = -lX11 -L$(TCL_DIR) -ltkx -ltk -ltclx -ltcl7.4 -litcl

LIBTK        = -ltk
LIBTCL       = -ltcl7.4
LIBTCLX      = -ltclx

#TCLLIBS = -ltcl
#TCLLIBS = $(LIBTK) $(LIBTCL) $(LIBTCLX)
TCLLIBS = $(TCL_LIB)

#### FLAGS ####

INVFLAGS     = $(FLAGS) -cckr -DINVENTOR -DUSTRACE 
#FLOCKFLAGS   = -DOPENGL -I/u/dave/libFlock2.0 -I/usr/include/Performer \
#	-Olimit 2000 

FLOCKFLAGS   = -DOPENGL -I/u/dave/libFlock -I/usr/include/Performer1.2 \
	-Olimit 2000 

IFLAGS       = -I$(EARL_TOPDIR)/include -I/usr/local/include \
	-I/vlw/pkg/tcl.installs/tcllib/include      

### Libs

tkXAppInit.o: tkXAppInit.cc
	$(CC) -I /usr/local/include -c tkXAppInit.cxx

### Individual compiles

PROGRAMS = test-fonts inventor_examp tcl_examp

$(PROGRAMS): $(APPLIBS) $$@.cxx
	$(CC) $(INVFLAGS) $(IFLAGS) -o $@ $@.cxx \
	$(INVLIBS) $(APPLIBS) $(TCLLIBS) $(TOOLS)

# Derives from TclX, gdd, tcl+gdbm, and my own extensions...

mywishx: tkXAppInit.o tcliv.o
	$(CC) $(INVFLAGS) tcliv.o tkXAppInit.o \
	gd1.2/tcl+gdbm/gdbmcmd.o gd1.2/gdCmd.o gd1.2/libgd.a -lgdbm \
	$(TCLLIBS) $(INVLIBS) -o mywishx 

#####

OBJS = 3wish.o w3shift.o w3core.o w3text.o w3bind.o w3textureobj.o w3rot.o\
	w3term.o w3flock.o w3kit.o w3lego.o

# Use gmake to successfully resolve the following

$(OBJS): 3wish.h 
	$(CC) $(INVFLAGS) $(FLOCKFLAGS) $(IFLAGS) -c $*.cxx

3wish: $(OBJS)
	$(CC) $(INVFLAGS) \
	3wish.o w3core.o w3shift.o w3text.o w3bind.o w3textureobj.o w3rot.o\
	w3term.o w3flock.o w3kit.o w3lego.o \
	gd1.2/tcl+gdbm/gdbmcmd.o gd1.2/gdCmd.o gd1.2/libgd.a -lgdbm \
	$(TCLLIBS) $(INVLIBS) $(APPLIBS) $(FLOCKLIB) $(LEGOLIB) -o 3wish


###
