# Tcl package index file, version 1.0
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

##Determine base directory

## at the moment, need to "lappend auto_path c:/users...tangeo.2/src" somewhere

namespace directories {
  set unixbase {/mas/tangible/src/proxdist.1/src/resources}
  set winbase  {/users/ullmer/src/tangeo.2/src/resources}
  set basedir  {}


  if {[file isdirectory $unixbase]} { 
    set basedir $unixbase
  } elseif {[file isdirectory $winbase]} {
    set basedir $winbase
  } else {
    puts "Problem in resources pkgIndex.tcl: cannot find valid basedir!"
    return
  }
}

## Package ifneeded assertions

package ifneeded tmg::base 1.0 {
  package require Itcl 2.1
  source [set directories::basedir]/base.tcl
}

package ifneeded tmg::hierarchy 1.0 {
  package require Itcl 2.1
  package require tmg::base
  source [set directories::basedir]/hierarchy.tcl
}

package ifneeded tmg::client 1.0 {
  package require Itcl 2.1
  package require Tclx
  source $basedir/client.tcl
}

package ifneeded tmg::server 1.0 {
  package require Itcl 2.1
  package require Tclx
  source $basedir/server.tcl
}

package ifneeded tmg:metadesk::coordinator 1.0 {
  package require Itcl 2.1
  package require Tclx
  source $basedir/coordinator.tcl
}

