#!/bin/bash

# Script generated by Microsoft Copilot on 2025-05-21
# Seemed to realize a >= 50% acceleration on an MS Surface Book 2 / Ubuntu 24 with moderately large surface scaling

# Exit immediately if a command exits with a non-zero status
set -e

# Add the Deadsnakes PPA for Python 3.11
sudo add-apt-repository ppa:deadsnakes/ppa -y
sudo apt update

# Install Python 3.11 and its tools
sudo apt install -y python3.11 python3.11-venv python3.11-dev python3.11-distutils

# Create a virtual environment with Python 3.11
python3.11 -m venv ~/pygame-avx2-env-py311
source ~/pygame-avx2-env-py311/bin/activate

# Install system build dependencies
sudo apt install -y build-essential cython3 libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libfreetype6-dev libavformat-dev libswscale-dev libjpeg-dev libpng-dev libtiff-dev libx11-dev libxext-dev libxi-dev libxrandr-dev libxinerama-dev libxcursor-dev libgl1-mesa-dev libgles2-mesa-dev libopenal-dev libasound2-dev libpulse-dev libudev-dev libdbus-1-dev libvorbis-dev libogg-dev libtheora-dev libsmpeg-dev

# Upgrade pip, setuptools, and wheel inside the virtual environment
pip install --upgrade pip setuptools wheel

# Set environment variables to enable AVX2 and force system distutils
export PYGAME_DETECT_AVX2=1
export SETUPTOOLS_USE_DISTUTILS=stdlib

# Install Pygame from source
pip install pygame --no-binary :all:

echo "Pygame with AVX2 support has been successfully installed!"
