# Tcl package index file, version 1.0
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

###################################################################
##################### Sensor Capabilities #########################
###################################################################

##################### Vision Capabilities #########################

package ifneeded tmg:metadesk::sensor:vision.visionlib 1.0 {
  #set localhost [exec hostname]
  set localhost [info hostname]

  if {![string match $localhost {gumby.media.mit.edu}]} {
    puts "tmg:metadesk::visionlib found, denied:"
    puts "execution local to gumby.media.mit.edu, you're on $localhost"
    puts "ignoring."
    return
  }

  load /mas/tangible/src/tangeo.2/src/sensors/vision/visionPackage.so
  package provide tmg:metadesk::sensor:vision.visionlib 1.0
}

### Tagtrack client/server ###

package ifneeded tmg:metadesk::sensor:tagtrack.server 1.0 {
  package require Itcl 2.1
  package require Tclx
  source /mas/tangible/src/tangeo.2/src/sensors/vision/tagtrackServer.tcl
}

package ifneeded tmg:metadesk::sensor:tagtrack.client 1.0 {
  package require Itcl 2.1
  package require Tclx
  source /mas/tangible/src/tangeo.2/src/sensors/vision/tagtrackClient.tcl
}

### Vision client/server ###

package ifneeded tmg:metadesk::sensor:vision.server 1.0 {
  package require Itcl 2.1
  package require Tclx
  source /mas/tangible/src/tangeo.2/src/sensors/vision/visionServer.tcl
}

package ifneeded tmg::graphview 1.0 {
  package require Itcl 2.1
  source /mas/tangible/src/tangeo.2/src/sensors/vision/graphview.tcl
}

##################### Flock Capabilities #########################

package ifneeded tmg:metadesk::sensor:flock.flocklib 1.0 {
  #set localhost [exec hostname]
  set localhost [info hostname]

  if {![string match $localhost {gumby.media.mit.edu}]} {
    puts "tmg:metadesk::visionlib found, denied:"
    puts "execution local to gumby.media.mit.edu, you're on $localhost"
    puts "ignoring."
    return
  }

  load /mas/tangible/src/tangeo.2/src/sensors/flock/flockPackage.so     
  package provide tmg:metadesk::sensor:flock.flocklib 1.0
}

package ifneeded tmg:metadesk::sensor:flock.server 1.0 {
  package require Itcl 2.1
  package require Tclx
  source /mas/tangible/src/tangeo.2/src/sensors/flock/flockServer.tcl
}

package ifneeded tmg:metadesk::sensor:flock.client 1.0 {
  package require Itcl 2.1
  package require Tclx
  source /mas/tangible/src/tangeo.2/src/sensors/flock/flockClient.tcl
}

package ifneeded tmg:metadesk::sensor:flock.calibrate 1.0 {
  package require Itcl 2.1
  source /mas/tangible/src/tangeo.2/src/sensors/flock/birdCalibrate.tcl
}


##################### Lego Capabilities #########################

package ifneeded tmg:metadesk::sensor:lego.legolib 1.0 {
  #set localhost [exec hostname]
  set localhost [info hostname]

  if {![string match $localhost {gumby.media.mit.edu}]} {
    puts "tmg:metadesk::visionlib found, denied:"
    puts "execution local to gumby.media.mit.edu, you're on $localhost"
    puts "ignoring."
    return
  }

  load /mas/tangible/src/tangeo.2/src/sensors/lego/legoPackage.so     
  package provide tmg:metadesk::sensor:lego.legolib 1.0
}

package ifneeded tmg:metadesk::sensor:lego.server 1.0 {
  package require Itcl 2.1
  package require Tclx
  source /mas/tangible/src/tangeo.2/src/sensors/lego/legoServer.tcl
}

package ifneeded tmg:metadesk::sensor:lego.client 1.0 {
  package require Itcl 2.1
  package require Tclx
  source /mas/tangible/src/tangeo.2/src/sensors/lego/legoClient.tcl
}

###################################################################
##################### Display Capabilities #########################
###################################################################

##################### Desk Capabilities #########################

package ifneeded tmg::canvsurface 1.0 {
  package require Itcl 
  #package require Tk
  source /mas/tangible/src/tangeo.2/src/displays/canvsurface/canvSurface.tcl
}

package ifneeded tmg::piemenuobj 1.0 {
  package require tmg::canvsurface
  source /mas/tangible/src/tangeo.2/src/displays/canvsurface/pieObj.tcl
}

### END ###

